version: "3.3"

services:
  go-book-store:
    build: ./src
    container_name: go-book-store
    ports:
      - 8080:8080
    environment:
      - MONGODB_CONNECTTION_URI: mongodb://root:root@mongodb-book-store:27017/?authSource=admin&w=majority&readPreference=primary&appname=MongoDB%20Compass&retryWrites=true&directConnection=true&ssl=false
      - JWT_LIFE_TIME: 7
      - JWT_SECRET: secret
    depends_on:
      - mongodb-book-store

  mongodb-book-store:
    image: mongo
    container_name: mongodb-book-store
    volumes:
      - ./mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
