// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// type Author struct {
// 	ID      string  `json:"id" bson:"_id,omitempty"`
// 	Name    string  `json:"name"`
// 	Created int64   `json:"created"`
// 	Updated int64   `json:"updated"`
// 	Books   []*Book `json:"books"`
// }

// type Book struct { 
// 	ID        string    `json:"id" bson:"_id,omitempty"`
// 	Name      string    `json:"name"`
// 	Content   string    `json:"content"`
// 	Created   int64     `json:"created"`
// 	Updated   int64     `json:"updated"`
// 	TopicsID  []string  `json:"topicsId"`
// 	AuthorsID []string  `json:"authorsId"`
// 	Topics    []*Topic  `json:"topics"`
// 	Authors   []*Author `json:"authors"`
// 	Reviews   []*Review `json:"reviews"`
// }

// type NewAuthor struct {
// 	Name string `json:"name"`
// }

// type NewBook struct {
// 	Name      string   `json:"name"`
// 	Content   string   `json:"content"`
// 	TopicsID  []string `json:"topicsId"`
// 	AuthorsID []string `json:"authorsId"`
// }

// type NewReview struct {
// 	Content string `json:"content"`
// 	BookID  string `json:"bookId"`
// }

// type NewTopic struct {
// 	Name string `json:"name"`
// }

// type Review struct {
// 	ID      string `json:"id" bson:"_id,omitempty"`
// 	Content string `json:"content"`
// 	Created int64  `json:"created"`
// 	Updated int64  `json:"updated"`
// 	BookID  string `json:"bookId"`
// }

// type Topic struct {
// 	ID      string  `json:"id" bson:"_id,omitempty"`
// 	Name    string  `json:"name"`
// 	Created int64   `json:"created"`
// 	Updated int64   `json:"updated"`
// 	Books   []*Book `json:"books"`
// }
